# Use the official Node.js image as the base image
FROM node:19-alpine

ARG ARG_NODE_ENV

ENV NODE_ENV=$ARG_NODE_ENV

# Needed for the wait-for-db script
RUN apk add --no-cache netcat-openbsd git
WORKDIR /workspace
RUN git clone https://github.com/reworkd/AgentGPT.git

# Set the working directory
WORKDIR /next

# Copy package.json and package-lock.json to the working directory
RUN cp /workspace/AgentGPT/next/package*.json ./

# Install dependencies
RUN npm ci

# Copy the wait-for-db.sh script
RUN cp /workspace/AgentGPT/next/wait-for-db.sh /usr/local/bin/wait-for-db.sh
RUN chmod +x /usr/local/bin/wait-for-db.sh

# Copy the rest of the application code
RUN cp -r /workspace/AgentGPT/next/* ./
RUN cp /workspace/AgentGPT/next/entrypoint.sh /

# Ensure correct line endings after these files are edited by windows
RUN apk add --no-cache dos2unix netcat-openbsd \
    && dos2unix /entrypoint.sh


# Expose the port the app will run on
EXPOSE 3000

ENTRYPOINT ["sh", "/entrypoint.sh"]

# Start the application
CMD ["npm", "run", "dev"]
